services:
  mysql-test:
    container_name: mysql-test
    image: mysql:8.0.33
    volumes:
      - ./db/mysql/conf.d:/etc/mysql/conf.d
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Seoul

  trader-api:
    container_name: trader-api
    build:
      dockerfile: Dockerfile-test
      context: ./trader-api
    image: kmnine3/trader-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
    restart: always
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mysql-test

  frontend:
    container_name: frontend
    image: kmnine3/frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always