services:
  mysql-prod:
    container_name: mysql-prod
    image: mysql:8.0.33
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
    #      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Seoul

  trader-api:
    container_name: trader-api
    build:
      dockerfile: Dockerfile-prod
      context: ./trader-api
    image: kmnine3/trader-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
    restart: always
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mysql-prod