services:
  trader-api:
    container_name: trader-api
    image: kmnine3/trader-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
    restart: always
    volumes:
      - ./logs:/app/logs