services:
  trader-api:
    container_name: trader-api
    image: kmnine3/trader-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
    restart: always
    volumes:
      - ./logs:/app/logs

  frontend:
    container_name: frontend
    image: kmnine3/frontend
    ports:
      - "3000:3000"
    restart: always

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./conf:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - trader-api
      - frontend