services:
  trader-api:
    container_name: trader-api
    build:
      dockerfile: Dockerfile-prod
      context: ./trader-api
    image: kmnine3/trader-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}
      - SELENIUM_REMOTE_URL=http://selenium-hub:4444/wd/hub
    depends_on:
      - selenium-hub
    restart: always
    volumes:
      - /Users/mingukang/dev/aws/log:/var/log   # 호스트 경로:컨테이너 경로

# https://github.com/SeleniumHQ/docker-selenium/releases
  selenium-hub:
    container_name: selenium-hub
    image: selenium/standalone-chromium:129.0.6668.58
    ports:
      - 4444:4444
    environment:
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=60