spring:
  profiles:
    group:
      local: common
      prod: common

upbit:
  access-key: ENC(lHKXPFsFLNHh4QtHXtYeRfnaG6EQyW5U0KJc/iiULcyespLw8rZ2JZUVV7TtWwec7TYOGDHuWXw=)
  secret-key: ENC(sWK04sCyy25gp91COo8EKpxwbVOlIGxl5b76M7+FTcklJUQgf2uXn+JDO38APHmlj8eYU4vhFSU=)

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/auto-trader?serverTimezone=Asia/Seoul&characterEncoding=utf8&postfileSQL=true&logger=Slf4JLogger&rewriteBatchedStatements=true
    username: ENC(Tdz4PPc1j9l2RGrP7ZN9sQ==)
    password: ENC(fT9yECXMC06Ys1UsGt8VFWDNwo++b+95)
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ENC(bYcAJIPcTt762iRnNb2pRlcJO/tc7SgajdzPihR1tIxHIDx/Zu2mlINkOJQZ/PDCpgpl6/P4RN3vw2hJBYdAgnikCWaXj8JBH8nli1d/FLGIyJabfWQ/i6AMrnOYcROEnlD0U3szJCAHMbeIkI5LGF8PxRMuIDb4ETGE5ud1jIJyqKUxf2JvXQrlpN9X44+47SNpYBaQa55CPX0n2ev08VSb25W4la8wh6m+gv6r/JxnhHZfPklwZVLMloO62DOIxza3Fd3hk3qD7YA95O+6X4ZcrzjVvSFQ)
    username: ENC(BGVkI48/zV3TRwwETjTgqw==)
    password: ENC(ABwAO7ge6mHACZYRNQcqGetEvrbSG1x8)
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: test