spring:
  profiles:
    group:
      local: common
      prod: common

upbit:
  access-key: ENC(lHKXPFsFLNHh4QtHXtYeRfnaG6EQyW5U0KJc/iiULcyespLw8rZ2JZUVV7TtWwec7TYOGDHuWXw=)
  secret-key: ENC(sWK04sCyy25gp91COo8EKpxwbVOlIGxl5b76M7+FTcklJUQgf2uXn+JDO38APHmlj8eYU4vhFSU=)

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/auto_trader?serverTimezone=Asia/Seoul&characterEncoding=utf8&postfileSQL=true&logger=Slf4JLogger&rewriteBatchedStatements=true
    username: ENC(Tdz4PPc1j9l2RGrP7ZN9sQ==)
    password: ENC(fT9yECXMC06Ys1UsGt8VFWDNwo++b+95)
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ENC(CDRccZnw9tudEaQaltSh4H+/gRQxnV/A9kDwu/9G5gj2IMTVqluGDdq2LyaapoGfwbcicRUaKEqOStesBirpx9tj2FmiDnKLEag0PuDGrbcIzhYTxZPd/SE69FJLLaf88+faDWNGTMeKe6MpHcofiQ==)
    username: ENC(+CYuu8jLTg6PHOH/nH6OXw==)
    password: ENC(UF4Z0xMHIXFKmC0Jm8EQxglufSt20xDI)
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://localhost:3306/auto_trader?serverTimezone=Asia/Seoul&characterEncoding=utf8&postfileSQL=true&logger=Slf4JLogger&rewriteBatchedStatements=true
    username: ENC(Tdz4PPc1j9l2RGrP7ZN9sQ==)
    password: ENC(fT9yECXMC06Ys1UsGt8VFWDNwo++b+95)
    driver-class-name: com.mysql.cj.jdbc.Driver