spring:
  profiles:
    group:
      local: common, domain, infra
      prod: common, domain, infra

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: test