# github repository Actions 페이지에 나타낼 이름
name: CI/CD

# event trigger
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:

    ## jdk setting
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin' # https://github.com/actions/setup-java

    ## gradle caching
    - name: Gradle Caching
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    ## gradle build
    - name: Build with Gradle
      run: ./gradlew clean :trader-api:buildNeeded --stacktrace --info --refresh-dependencies -x test

    ## Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.14.0'

    ## Install dependencies and build NextJS app
    - name: Install and build NextJS app
      run: |
        cd ./frontend/auto-trader  # Adjust this path if your NextJS app is in a different directory
        yarn install
        yarn build

    ## docker build & push to production
    - name: Docker build & push to prod
      if: contains(github.ref, 'main')
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -f ./trader-api/Dockerfile -t ${{ secrets.DOCKER_REPO }}/trader-api .
        docker push ${{ secrets.DOCKER_REPO }}/trader-api
        docker build --progress=plain -f ./frontend/Dockerfile -t ${{ secrets.DOCKER_REPO }}/frontend ./frontend
        docker push ${{ secrets.DOCKER_REPO }}/frontend

    ## AWS EC2에 접속하고 develop을 배포합니다.
    - name: Deploy to prod
      uses: appleboy/ssh-action@master
      id: deploy-prod
      env:
        COMPOSE: "/home/ubuntu/app/docker-compose.yml"
      if: contains(github.ref, 'main')
      with:
          host: ${{ secrets.EC2_SSH_HOST_NAME }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          envs: COMPOSE
          script: |
            sudo docker stop $(sudo docker ps -a -q)
            sudo docker rm $(sudo docker ps -a -q)
            sudo docker rmi $(sudo docker images -q)
            sudo docker pull ${{ secrets.DOCKER_REPO }}/trader-api
            sudo docker pull ${{ secrets.DOCKER_REPO }}/frontend
            sudo docker-compose -f $COMPOSE up --build -d
            sudo docker image prune -f
