FROM openjdk:21

# 작업 디렉토리를 설정
WORKDIR /app

# 로그 디렉토리 생성
RUN mkdir -p /app/logs /app/logs/archived

# 포트 오픈
EXPOSE 8080

# 어플리케이션 JAR 복사 및 설정
ARG JAR_FILE=build/libs/auto-trader-app.jar
COPY ${JAR_FILE} /app/app.jar
ENV TZ=Asia/Seoul

# 어플리케이션 실행
ENTRYPOINT ["java", "-jar", "/app/app.jar"]